Use coalesce() to reconfigure image_id variable
FitnessKeeper/terraform-rk-app pull request #6
Opened 2023-03-03 17:00 UTC by SaiPrasannaGopularam

# Changes
- Use coalesce() to either use the existing AMI ID or the one passed from the module

2023-03-03 17:05 UTC, automationforthepeople requested changes
this is dangerous the way it is. It needs to be looking that up from what exists. Not hardcoded

2023-03-03 17:05 UTC, temmydev262 approved these changes

2023-03-03 17:07 UTC, automationforthepeople commented on main.tf
> +    values = ["tomcat-webapi-312"]
why not use the same coalesce here?

2023-03-03 17:08 UTC, automationforthepeople commented on main.tf
> +    values = ["tomcat-webapi-312"]
this will break deploying by ami id

2023-03-03 17:11 UTC, automationforthepeople commented on main.tf
> +  image_id                    = coalesce(var.ami_id, data.aws_ami.app.id)
I would actually leave this as is and do all my coalesce smarts in the data object. this may be tricky and require a 2nd data object that only is used or exists when `var.ami_id,` is null

2023-03-10 17:55 UTC, SaiPrasannaGopularam commented
Logic changed and created another PR to create and fetch the ami id from an aws_ssm_param

2023-03-10 17:55 UTC, closed without merging